classes:
  rev::spark::AbsoluteEncoderConfigAccessor:
    methods:
      GetInverted:
      GetAverageDepth:
      GetStartPulseUs:
      GetEndPulseUs:
      GetZeroOffset:
      IsZeroCentered:
      GetRangeOffset:
