

// This file is autogenerated. DO NOT EDIT

#pragma once
#include <robotpy_build.h>

#include <rev\CANSensor.h>



namespace rpygen {

using namespace rev;

template <typename CxxBase>
struct Pyrev__CANSensor : CxxBase {
    using CxxBase::CxxBase;



#ifndef RPYGEN_DISABLE_SetInverted_b
    CANError SetInverted(bool inverted) override {
PYBIND11_OVERLOAD_PURE_NAME(CANError, CxxBase, "setInverted", SetInverted,inverted);
    }
#endif

#ifndef RPYGEN_DISABLE_KGetInverted_v
    bool GetInverted() const override {
PYBIND11_OVERLOAD_PURE_NAME(bool, CxxBase, "getInverted", GetInverted,);
    }
#endif

#ifndef RPYGEN_DISABLE_KGetID_v
    int GetID() const override {
PYBIND11_OVERLOAD_PURE_NAME(int, CxxBase, "_getID", GetID,);
    }
#endif



    using rev::CANSensor::m_device;
};

}; // namespace rpygen