

// This file is autogenerated. DO NOT EDIT

#pragma once
#include <robotpy_build.h>

#include <rev\SparkMax.h>


#include <rpygen/frc__PWMSpeedController.hpp>

namespace rpygen {

using namespace rev;

template <typename CxxBase>
using PyBaserev__SparkMax = 
    Pyfrc__PWMSpeedController<
        CxxBase
    >
;

template <typename CxxBase>
struct Pyrev__SparkMax : PyBaserev__SparkMax<CxxBase> {
    using PyBaserev__SparkMax<CxxBase>::PyBaserev__SparkMax;





};

}; // namespace rpygen