

// This file is autogenerated. DO NOT EDIT

#pragma once
#include <robotpy_build.h>

#include <rev\CANSparkMax.h>


#include <rpygen/rev__CANSparkMaxLowLevel.hpp>

namespace rpygen {

using namespace rev;

template <typename CxxBase>
using PyBaserev__CANSparkMax = 
    Pyrev__CANSparkMaxLowLevel<
        CxxBase
    >
;

template <typename CxxBase>
struct Pyrev__CANSparkMax : PyBaserev__CANSparkMax<CxxBase> {
    using PyBaserev__CANSparkMax<CxxBase>::PyBaserev__CANSparkMax;



#ifndef RPYGEN_DISABLE_Set_d
    void Set(double speed) override {
PYBIND11_OVERLOAD_NAME(void, CxxBase, "set", Set,speed);
    }
#endif

#ifndef RPYGEN_DISABLE_SetVoltage_Tunits__volt_t
    void SetVoltage(units::volt_t output) override {
PYBIND11_OVERLOAD_NAME(void, CxxBase, "setVoltage", SetVoltage,output);
    }
#endif

#ifndef RPYGEN_DISABLE_KGet_v
    double Get() const override {
PYBIND11_OVERLOAD_NAME(double, CxxBase, "get", Get,);
    }
#endif

#ifndef RPYGEN_DISABLE_SetInverted_b
    void SetInverted(bool isInverted) override {
PYBIND11_OVERLOAD_NAME(void, CxxBase, "setInverted", SetInverted,isInverted);
    }
#endif

#ifndef RPYGEN_DISABLE_KGetInverted_v
    bool GetInverted() const override {
PYBIND11_OVERLOAD_NAME(bool, CxxBase, "getInverted", GetInverted,);
    }
#endif

#ifndef RPYGEN_DISABLE_Disable_v
    void Disable() override {
PYBIND11_OVERLOAD_NAME(void, CxxBase, "disable", Disable,);
    }
#endif

#ifndef RPYGEN_DISABLE_StopMotor_v
    void StopMotor() override {
PYBIND11_OVERLOAD_NAME(void, CxxBase, "stopMotor", StopMotor,);
    }
#endif

#ifndef RPYGEN_DISABLE_PIDWrite_d
    void PIDWrite(double output) override {
PYBIND11_OVERLOAD_NAME(void, CxxBase, "PIDWrite", PIDWrite,output);
    }
#endif



};

}; // namespace rpygen