---

classes:
  AbsoluteEncoderConfig:
    methods:
      AbsoluteEncoderConfig:
      Apply:
      SetSparkMaxDataPortConfig:
      Inverted:
      PositionConversionFactor:
      VelocityConversionFactor:
      ZeroOffset:
      AverageDepth:
      StartPulseUs:
      EndPulseUs:
