---

classes:
  AbsoluteEncoderConfigAccessor:
    methods:
      GetInverted:
      GetPositionConversionFactor:
      GetVelocityConversionFactor:
      GetAverageDepth:
      GetStartPulseUs:
      GetEndPulseUs:
