---

classes:
  AlternateEncoderConfigAccessor:
    methods:
      GetCountsPerRevolution:
      GetInverted:
      GetPositionConversionFactor:
      GetVelocityConversionFactor:
      GetMeasurementPeriod:
