---

classes:
  EncoderConfig:
    base_qualnames:
      BaseConfig: rev::BaseConfig
    methods:
      EncoderConfig:
      Apply:
      CountsPerRevolution:
      Inverted:
      PositionConversionFactor:
      VelocityConversionFactor:
      QuadratureAverageDepth:
      QuadratureMeasurementPeriod:
      UvwAverageDepth:
      UvwMeasurementPeriod:
