---

classes:
  ExternalEncoderConfigAccessor:
    methods:
      GetCountsPerRevolution:
      GetInverted:
      GetPositionConversionFactor:
      GetVelocityConversionFactor:
      GetAverageDepth:
      GetMeasurementPeriod:
