---

classes:
  ExternalEncoderConfig:
    base_qualnames:
      BaseConfig: rev::BaseConfig
    enums:
      Type:
    methods:
      FromId:
      ExternalEncoderConfig:
      Apply:
      CountsPerRevolution:
      Inverted:
      PositionConversionFactor:
      VelocityConversionFactor:
      AverageDepth:
      MeasurementPeriod:
