---

classes:
  LimitSwitchConfig:
    enums:
      Type:
    methods:
      LimitSwitchConfig:
      Apply:
      SetSparkMaxDataPortConfig:
      ForwardLimitSwitchEnabled:
      ForwardLimitSwitchType:
      ReverseLimitSwitchEnabled:
      ReverseLimitSwitchType:
