---

classes:
  MAXMotionConfig:
    enums:
      MAXMotionPositionMode:
    methods:
      MAXMotionConfig:
      Apply:
      MaxVelocity:
      MaxAcceleration:
      AllowedClosedLoopError:
      PositionMode:
