---

classes:
  MAXMotionConfig:
    base_qualnames:
      BaseConfig: rev::BaseConfig
    enums:
      MAXMotionPositionMode:
    methods:
      MAXMotionConfig:
      Apply:
      MaxVelocity:
      MaxAcceleration:
      AllowedClosedLoopError:
      PositionMode:
