---

classes:
  SmartMotionConfig:
    base_qualnames:
      BaseConfig: rev::BaseConfig
    methods:
      SmartMotionConfig:
      Apply:
      MaxVelocity:
      MaxAcceleration:
      MinOutputVelocity:
      AllowedClosedLoopError:
