---

classes:
  SparkFlexConfig:
    attributes:
      externalEncoder:
    methods:
      SparkFlexConfig:
      Apply:
        overloads:
          SparkFlexConfig&:
          ExternalEncoderConfig&:
      Flatten:
