---

classes:
  SparkMaxConfig:
    attributes:
      alternateEncoder:
    enums:
      DataPortConfig:
    methods:
      SparkMaxConfig:
      Apply:
        overloads:
          SparkMaxConfig&:
          AlternateEncoderConfig&:
      Flatten:
